name = "GMAT"
uuid = "af5f6e49-cefe-43d6-ba7f-e98344787928"
authors = ["Helge Eichhorn <git@helgeeichhorn.de>"]
version = "0.1.0"

[deps]
GMAT_jll = "5472d9e0-cb42-52f7-96c9-a9fd19db341f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.3"
GMAT_jll = "2020"
